name: Manual Facebook Ad Scraper

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the scraper'
        required: false
        default: 'Manual trigger'

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hour timeout
    permissions:
      contents: write  # Required to push commits

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Make run_scraper.sh executable
        run: chmod +x run_scraper.sh

      - name: Run scraper script
        run: ./run_scraper.sh

      - name: Commit and push new data
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Check if there are any new or modified files in the contents directory
          if [[ -n $(git status --porcelain contents/) ]]; then
            # Add new/modified files in the contents directory
            git add contents/
            
            # Get today's date for the commit message
            TODAY=$(date +"%Y-%m-%d")
            
            # Commit with a descriptive message including the date
            git commit -m "Add scraper results for $TODAY"
            
            # Push changes to the repository
            git push
            
            echo "Successfully committed and pushed new data"
          else
            echo "No new data to commit"
          
